[package]
name = "rfc-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }

anyhow = "1.0.54"

serde = "1.0.136"
serde_json = "1.0.79"

reqwest = { version = "0.11" }
scraper = "0.12.0"

petgraph = "0.6.0"

tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.8"

async-stream = "0.3.2"
async-recursion = "1.0.0"
