allow-branch = ["*", "!HEAD"]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = true
verify = true
push = true
push-options = []
shared-version = false
consolidate-commits = false
pre-release-commit-message = "(cargo-release) version {{version}}"
tag-message = "(cargo-release) {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "fix"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace = "{{version}}"
prerelease = true

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace = "{{date}}"
prerelease = true

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = """
<!-- next-header -->

## [Unreleased] - ReleaseDate"""
exactly = 1
prerelease = true
