name: Release
on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  release-crates-io:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get bump method
        run: |
          if [ ${{ github.event.label.name == 'bump: Candidate' }} ]; then
            echo '::set-output name=BUMP::rc'
          elif [ ${{ github.event.label.name == 'bump: Patch' }} ]; then
            echo '::set-output name=BUMP::patch'
          elif [ ${{ github.event.label.name == 'bump: Minor' }} ]; then
            echo '::set-output name=BUMP::minor'
          elif [ ${{ github.event.label.name == 'bump: Major' }} ]; then
            echo '::set-output name=BUMP::major'
          else
            exit 1
          fi
        id: get-bump-method
      - run: echo "The selected bump is ${{ steps.get-bump-method.outputs.BUMP }}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
          commit-filter: "(cargo-release)"
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db/
            ./target
          key: "${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-release
      - run: |
          git config --global user.name 'Mathieu LALA [bot]'
          git config --global user.email 'mathieu.lala@epitech.eu'
      - run: cargo release ${{ steps.get-bump-method.outputs.BUMP }} --workspace --execute --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
