name: Release
on:
  pull_request:
    branches:
      - "main"
    types: [closed]

env:
  LABEL_CANDIDATE: "bump: Candidate"
  LABEL_PATCH: "bump: Patch"
  LABEL_MINOR: "bump: Minor"
  LABEL_MAJOR: "bump: Major"

jobs:
  release-crates-io:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get bump method
        if: contains(github.event.pull_request.labels.*.name, '$LABEL_CANDIDATE')
        run: echo '::set-output name=BUMP::rc'
        id: get-bump-method
      - name: Get bump method
        if: contains(github.event.pull_request.labels.*.name, '$LABEL_PATCH')
        run: echo '::set-output name=BUMP::patch'
        id: get-bump-method
      - name: Get bump method
        if: contains(github.event.pull_request.labels.*.name, '$LABEL_MINOR')
        run: echo '::set-output name=BUMP::minor'
        id: get-bump-method
      - name: Get bump method
        if: contains(github.event.pull_request.labels.*.name, '$LABEL_MAJOR')
        run: echo '::set-output name=BUMP::major'
        id: get-bump-method
      - run: echo "The selected bump is ${{ steps.get-bump-method.outputs.BUMP }}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
          commit-filter: "(cargo-release)"
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db/
            ./target
          key: "${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-release
      - run: |
          git config --global user.name 'Mathieu LALA [bot]'
          git config --global user.email 'mathieu.lala@epitech.eu'
      - run: cargo release ${{ steps.get-bump-method.outputs.BUMP }} --workspace --execute --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
